/* Generated by Yosys 0.9+3871 (git sha1 98afe2b7, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module circuit(clk, x, y, z);
  input clk;
  wire r;
  wire t;
  input x;
  input y;
  output z;
  XOR _0_ (
    .A(y),
    .B(x),
    .Y(t)
  );
  BUF _1_ (
    .A(r),
    .Y(z)
  );
  DFF _2_ (
    .C(clk),
    .D(t),
    .Q(r)
  );
endmodule
