/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module circuit(a, b, c, d, q, CLK);
  output q;
  wire q;
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  input d;
  wire d;
  wire y1;
  wire y2;
  input clk;
  wire clk;

  sky130_fd_sc_hd__and2_2 _0_ (
    .A(a),
    .B(b),
    .X(y1)
  );
  sky130_fd_sc_hd__and2_2 _1_ (
    .A(c),
    .B(d),
    .X(y2)
  );
  sky130_fd_sc_hd__xor2_2 _2_ (
    .A(y1),
    .B(y2),
    .X(q)
  );
endmodule
