/* Generated by Yosys 0.9+3871 (git sha1 98afe2b7, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "../../test/top.v:38.1-54.10" *)
module top(clk, a0, a1, b0, b1, x0, x1, y0, y1, r0, r1, z0, z1);
  (* keep_hierarchy = 32'd0 *)
  wire _00_;
  (* keep_hierarchy = 32'd0 *)
  wire _01_;
  (* keep_hierarchy = 32'd0 *)
  wire _02_;
  (* keep_hierarchy = 32'd0 *)
  wire _03_;
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:40.11-40.13" *)
  input a0;
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:42.11-42.13" *)
  input a1;
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:41.11-41.13" *)
  input b0;
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:43.11-43.13" *)
  input b1;
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:47.10-47.12" *)
  wire c0;
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:47.14-47.16" *)
  wire c1;
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:39.11-39.14" *)
  input clk;
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:47.18-47.20" *)
  wire d0;
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:47.22-47.24" *)
  wire d1;
  (* hdlname = "inst0 clk" *)
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:49.13-49.91|../../test/top.v:2.11-2.14" *)
  wire \inst0.clk ;
  (* hdlname = "inst0 r" *)
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:49.13-49.91|../../test/top.v:7.11-7.12" *)
  wire \inst0.r ;
  (* hdlname = "inst0 r0" *)
  (* keep_hierarchy = 32'd0 *)
  (* share_domain = 32'd0 *)
  (* src = "../../test/top.v:49.13-49.91|../../test/top.v:11.32-11.34" *)
  wire \inst0.r0 ;
  (* hdlname = "inst0 r1" *)
  (* keep_hierarchy = 32'd0 *)
  (* share_domain = 32'd1 *)
  (* src = "../../test/top.v:49.13-49.91|../../test/top.v:12.32-12.34" *)
  wire \inst0.r1 ;
  (* hdlname = "inst0 r2" *)
  (* keep_hierarchy = 32'd0 *)
  (* share_domain = 32'd2 *)
  (* src = "../../test/top.v:49.13-49.91|../../test/top.v:13.32-13.34" *)
  wire \inst0.r2 ;
  (* hdlname = "inst0 r3" *)
  (* keep_hierarchy = 32'd0 *)
  (* share_domain = 32'd3 *)
  (* src = "../../test/top.v:49.13-49.91|../../test/top.v:14.32-14.34" *)
  wire \inst0.r3 ;
  (* hdlname = "inst0 t0" *)
  (* keep_hierarchy = 32'd0 *)
  (* share_domain = 32'd0 *)
  (* src = "../../test/top.v:49.13-49.91|../../test/top.v:16.33-16.35" *)
  wire \inst0.t0 ;
  (* hdlname = "inst0 t1" *)
  (* keep_hierarchy = 32'd0 *)
  (* share_domain = 32'd1 *)
  (* src = "../../test/top.v:49.13-49.91|../../test/top.v:17.33-17.35" *)
  wire \inst0.t1 ;
  (* hdlname = "inst0 t2" *)
  (* keep_hierarchy = 32'd0 *)
  (* share_domain = 32'd2 *)
  (* src = "../../test/top.v:49.13-49.91|../../test/top.v:18.33-18.35" *)
  wire \inst0.t2 ;
  (* hdlname = "inst0 t3" *)
  (* keep_hierarchy = 32'd0 *)
  (* share_domain = 32'd3 *)
  (* src = "../../test/top.v:49.13-49.91|../../test/top.v:19.33-19.35" *)
  wire \inst0.t3 ;
  (* hdlname = "inst0 x0" *)
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:49.13-49.91|../../test/top.v:3.11-3.13" *)
  wire \inst0.x0 ;
  (* hdlname = "inst0 x1" *)
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:49.13-49.91|../../test/top.v:5.11-5.13" *)
  wire \inst0.x1 ;
  (* hdlname = "inst0 y0" *)
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:49.13-49.91|../../test/top.v:4.11-4.13" *)
  wire \inst0.y0 ;
  (* hdlname = "inst0 y1" *)
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:49.13-49.91|../../test/top.v:6.11-6.13" *)
  wire \inst0.y1 ;
  (* hdlname = "inst0 z0" *)
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:49.13-49.91|../../test/top.v:8.12-8.14" *)
  wire \inst0.z0 ;
  (* hdlname = "inst0 z1" *)
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:49.13-49.91|../../test/top.v:9.12-9.14" *)
  wire \inst0.z1 ;
  (* hdlname = "inst1 clk" *)
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:50.13-50.91|../../test/top.v:2.11-2.14" *)
  wire \inst1.clk ;
  (* hdlname = "inst1 r" *)
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:50.13-50.91|../../test/top.v:7.11-7.12" *)
  wire \inst1.r ;
  (* hdlname = "inst1 r0" *)
  (* keep_hierarchy = 32'd0 *)
  (* share_domain = 32'd0 *)
  (* src = "../../test/top.v:50.13-50.91|../../test/top.v:11.32-11.34" *)
  wire \inst1.r0 ;
  (* hdlname = "inst1 r1" *)
  (* keep_hierarchy = 32'd0 *)
  (* share_domain = 32'd1 *)
  (* src = "../../test/top.v:50.13-50.91|../../test/top.v:12.32-12.34" *)
  wire \inst1.r1 ;
  (* hdlname = "inst1 r2" *)
  (* keep_hierarchy = 32'd0 *)
  (* share_domain = 32'd2 *)
  (* src = "../../test/top.v:50.13-50.91|../../test/top.v:13.32-13.34" *)
  wire \inst1.r2 ;
  (* hdlname = "inst1 r3" *)
  (* keep_hierarchy = 32'd0 *)
  (* share_domain = 32'd3 *)
  (* src = "../../test/top.v:50.13-50.91|../../test/top.v:14.32-14.34" *)
  wire \inst1.r3 ;
  (* hdlname = "inst1 t0" *)
  (* keep_hierarchy = 32'd0 *)
  (* share_domain = 32'd0 *)
  (* src = "../../test/top.v:50.13-50.91|../../test/top.v:16.33-16.35" *)
  wire \inst1.t0 ;
  (* hdlname = "inst1 t1" *)
  (* keep_hierarchy = 32'd0 *)
  (* share_domain = 32'd1 *)
  (* src = "../../test/top.v:50.13-50.91|../../test/top.v:17.33-17.35" *)
  wire \inst1.t1 ;
  (* hdlname = "inst1 t2" *)
  (* keep_hierarchy = 32'd0 *)
  (* share_domain = 32'd2 *)
  (* src = "../../test/top.v:50.13-50.91|../../test/top.v:18.33-18.35" *)
  wire \inst1.t2 ;
  (* hdlname = "inst1 t3" *)
  (* keep_hierarchy = 32'd0 *)
  (* share_domain = 32'd3 *)
  (* src = "../../test/top.v:50.13-50.91|../../test/top.v:19.33-19.35" *)
  wire \inst1.t3 ;
  (* hdlname = "inst1 x0" *)
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:50.13-50.91|../../test/top.v:3.11-3.13" *)
  wire \inst1.x0 ;
  (* hdlname = "inst1 x1" *)
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:50.13-50.91|../../test/top.v:5.11-5.13" *)
  wire \inst1.x1 ;
  (* hdlname = "inst1 y0" *)
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:50.13-50.91|../../test/top.v:4.11-4.13" *)
  wire \inst1.y0 ;
  (* hdlname = "inst1 y1" *)
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:50.13-50.91|../../test/top.v:6.11-6.13" *)
  wire \inst1.y1 ;
  (* hdlname = "inst1 z0" *)
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:50.13-50.91|../../test/top.v:8.12-8.14" *)
  wire \inst1.z0 ;
  (* hdlname = "inst1 z1" *)
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:50.13-50.91|../../test/top.v:9.12-9.14" *)
  wire \inst1.z1 ;
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:44.11-44.13" *)
  input r0;
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:44.15-44.17" *)
  input r1;
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:40.15-40.17" *)
  input x0;
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:42.15-42.17" *)
  input x1;
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:41.15-41.17" *)
  input y0;
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:43.15-43.17" *)
  input y1;
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:45.12-45.14" *)
  output z0;
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:45.16-45.18" *)
  output z1;
  (* keep_hierarchy = 32'd0 *)
  XOR _04_ (
    .A(d0),
    .B(c0),
    .Y(z0)
  );
  (* keep_hierarchy = 32'd0 *)
  XOR _05_ (
    .A(d1),
    .B(c1),
    .Y(z1)
  );
  (* keep_hierarchy = 32'd0 *)
  NAND _06_ (
    .A(\inst0.y1 ),
    .B(\inst0.x0 ),
    .Y(_00_)
  );
  (* keep_hierarchy = 32'd0 *)
  XNOR _07_ (
    .A(\inst0.r ),
    .B(_00_),
    .Y(\inst0.t1 )
  );
  (* keep_hierarchy = 32'd0 *)
  NAND _08_ (
    .A(\inst0.x1 ),
    .B(\inst0.y0 ),
    .Y(_01_)
  );
  (* keep_hierarchy = 32'd0 *)
  XNOR _09_ (
    .A(\inst0.r ),
    .B(_01_),
    .Y(\inst0.t2 )
  );
  (* keep_hierarchy = 32'd0 *)
  AND _10_ (
    .A(\inst0.y1 ),
    .B(\inst0.x1 ),
    .Y(\inst0.t3 )
  );
  (* keep_hierarchy = 32'd0 *)
  XOR _11_ (
    .A(\inst0.r1 ),
    .B(\inst0.r0 ),
    .Y(\inst0.z0 )
  );
  (* keep_hierarchy = 32'd0 *)
  XOR _12_ (
    .A(\inst0.r3 ),
    .B(\inst0.r2 ),
    .Y(\inst0.z1 )
  );
  (* keep_hierarchy = 32'd0 *)
  AND _13_ (
    .A(\inst0.x0 ),
    .B(\inst0.y0 ),
    .Y(\inst0.t0 )
  );
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:49.13-49.91|../../test/top.v:29.5-35.8" *)
  DFF _14_ (
    .C(\inst0.clk ),
    .D(\inst0.t3 ),
    .Q(\inst0.r3 )
  );
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:49.13-49.91|../../test/top.v:29.5-35.8" *)
  DFF _15_ (
    .C(\inst0.clk ),
    .D(\inst0.t0 ),
    .Q(\inst0.r0 )
  );
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:49.13-49.91|../../test/top.v:29.5-35.8" *)
  DFF _16_ (
    .C(\inst0.clk ),
    .D(\inst0.t1 ),
    .Q(\inst0.r1 )
  );
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:49.13-49.91|../../test/top.v:29.5-35.8" *)
  DFF _17_ (
    .C(\inst0.clk ),
    .D(\inst0.t2 ),
    .Q(\inst0.r2 )
  );
  (* keep_hierarchy = 32'd0 *)
  NAND _18_ (
    .A(\inst1.y1 ),
    .B(\inst1.x0 ),
    .Y(_02_)
  );
  (* keep_hierarchy = 32'd0 *)
  XNOR _19_ (
    .A(\inst1.r ),
    .B(_02_),
    .Y(\inst1.t1 )
  );
  (* keep_hierarchy = 32'd0 *)
  NAND _20_ (
    .A(\inst1.x1 ),
    .B(\inst1.y0 ),
    .Y(_03_)
  );
  (* keep_hierarchy = 32'd0 *)
  XNOR _21_ (
    .A(\inst1.r ),
    .B(_03_),
    .Y(\inst1.t2 )
  );
  (* keep_hierarchy = 32'd0 *)
  AND _22_ (
    .A(\inst1.y1 ),
    .B(\inst1.x1 ),
    .Y(\inst1.t3 )
  );
  (* keep_hierarchy = 32'd0 *)
  XOR _23_ (
    .A(\inst1.r1 ),
    .B(\inst1.r0 ),
    .Y(\inst1.z0 )
  );
  (* keep_hierarchy = 32'd0 *)
  XOR _24_ (
    .A(\inst1.r3 ),
    .B(\inst1.r2 ),
    .Y(\inst1.z1 )
  );
  (* keep_hierarchy = 32'd0 *)
  AND _25_ (
    .A(\inst1.x0 ),
    .B(\inst1.y0 ),
    .Y(\inst1.t0 )
  );
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:50.13-50.91|../../test/top.v:29.5-35.8" *)
  DFF _26_ (
    .C(\inst1.clk ),
    .D(\inst1.t3 ),
    .Q(\inst1.r3 )
  );
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:50.13-50.91|../../test/top.v:29.5-35.8" *)
  DFF _27_ (
    .C(\inst1.clk ),
    .D(\inst1.t0 ),
    .Q(\inst1.r0 )
  );
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:50.13-50.91|../../test/top.v:29.5-35.8" *)
  DFF _28_ (
    .C(\inst1.clk ),
    .D(\inst1.t1 ),
    .Q(\inst1.r1 )
  );
  (* keep_hierarchy = 32'd0 *)
  (* src = "../../test/top.v:50.13-50.91|../../test/top.v:29.5-35.8" *)
  DFF _29_ (
    .C(\inst1.clk ),
    .D(\inst1.t2 ),
    .Q(\inst1.r2 )
  );
  assign \inst1.clk  = clk;
  assign \inst1.r  = r1;
  assign \inst1.x0  = x0;
  assign \inst1.x1  = x1;
  assign \inst1.y0  = y0;
  assign \inst1.y1  = y1;
  assign d0 = \inst1.z0 ;
  assign d1 = \inst1.z1 ;
  assign \inst0.clk  = clk;
  assign \inst0.r  = r0;
  assign \inst0.x0  = a0;
  assign \inst0.x1  = a1;
  assign \inst0.y0  = b0;
  assign \inst0.y1  = b1;
  assign c0 = \inst0.z0 ;
  assign c1 = \inst0.z1 ;
endmodule
